<a href="https://colab.research.google.com/github/Lorenzito/ProgramacionParaAnaliticaDescriptivayPredicitva/blob/main/S06_Actividad_02_ALGEBRALINEAL_273524.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---

Lorenzo Varela Ollervides - 273524
---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [38]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [39]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [40]:
# Tu código aquí

# Calculamos la norma (magnitud) de cada vector usando np.linalg.norm()
norma_A = np.linalg.norm(producto_A)
norma_B = np.linalg.norm(producto_B)
norma_C = np.linalg.norm(producto_C)

print("Norma de producto_A:", norma_A)
print("Norma de producto_B:", norma_B)
print("Norma de producto_C:", norma_C)

Norma de producto_A: 7.449161026585477
Norma de producto_B: 6.777167549942971
Norma de producto_C: 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [41]:
# Tu código aquí

# 1. Producto punto entre producto_A y producto_B, y entre producto_A y producto_C
dot_AB = producto_A @ producto_B
dot_AC = producto_A @ producto_C

print("Producto punto A·B:", dot_AB)
print("Producto punto A·C:", dot_AC)
print("-" * 30)

# 2. Ángulo entre los vectores, usando la fórmula:
#    cos(θ) = (A·B) / (||A|| * ||B||)
#    Usamos np.linalg.norm() para la magnitud de cada vector,
#    np.arccos() para obtener el ángulo en radianes,
#    y np.degrees() para convertirlo a grados.

angulo_AB = np.degrees(np.arccos(dot_AB / (norma_A * norma_B)))
angulo_AC = np.degrees(np.arccos(dot_AC / (norma_A * norma_C)))

print("Ángulo entre A y B (grados):", angulo_AB)
print("Ángulo entre A y C (grados):", angulo_AC)


Producto punto A·B: 50.46
Producto punto A·C: 26.5
------------------------------
Ángulo entre A y B (grados): 1.7745815839558179
Ángulo entre A y C (grados): 47.22509268261831


El producto **B** es más similar a `producto_A`, ya que el ángulo entre A y B es considerablemente menor que el ángulo entre A y C.

El ángulo es el indicador correcto para esta comparación porque mide la similitud en la **dirección** (proporción entre componentes) de los vectores, sin verse afectado por su magnitud. Dos vectores pueden tener normas muy distintas, pero si sus componentes guardan proporciones similares entre sí, apuntarán en una dirección parecida y el ángulo entre ellos será pequeño.

En este caso, `producto_A` y `producto_B` mantienen una proporción similar entre sus tres componentes, por eso el ángulo entre ambos es pequeño (alta similitud). `producto_C`, en cambio, tiene una distribución distinta entre sus componentes (su segundo valor es proporcionalmente mucho más alto que los otros dos), lo que genera un ángulo mayor respecto a A, indicando menor similitud direccional.

---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [42]:
# Tu código aquí

# Normalizamos cada vector dividiéndolo entre su propia norma (magnitud),
# obteniendo así un vector unitario (misma dirección, magnitud = 1)
producto_A_normalizado = producto_A / norma_A
producto_B_normalizado = producto_B / norma_B
producto_C_normalizado = producto_C / norma_C

print("Producto A normalizado:", producto_A_normalizado)
print("Producto B normalizado:", producto_B_normalizado)
print("Producto C normalizado:", producto_C_normalizado)
print("-" * 30)

# Verificamos que la norma de cada vector normalizado sea 1, usando np.linalg.norm()
print("Norma de A normalizado:", np.linalg.norm(producto_A_normalizado))
print("Norma de B normalizado:", np.linalg.norm(producto_B_normalizado))
print("Norma de C normalizado:", np.linalg.norm(producto_C_normalizado))

Producto A normalizado: [0.60409488 0.42957858 0.67121653]
Producto B normalizado: [0.59021707 0.41315195 0.69350506]
Producto C normalizado: [0.19090089 0.95450444 0.22908106]
------------------------------
Norma de A normalizado: 1.0
Norma de B normalizado: 1.0
Norma de C normalizado: 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [43]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [44]:
# Tu código aquí

# 1. Multiplicación elemento a elemento vs multiplicación matricial
mult_elemento = M * P
mult_matricial = M @ P

print("M * P (elemento a elemento):")
print(mult_elemento)
print("-" * 30)
print("M @ P (multiplicación matricial):")
print(mult_matricial)


M * P (elemento a elemento):
[[3. 0.]
 [0. 6.]]
------------------------------
M @ P (multiplicación matricial):
[[3.  2. ]
 [1.5 6. ]]


`M * P` y `M @ P` dan resultados distintos porque son operaciones diferentes:

- `M * P` es una multiplicación **elemento a elemento**: cada elemento de `M` se multiplica únicamente con el elemento que está en la misma posición (fila, columna) de `P`. Para que esto funcione, ambas matrices deben tener exactamente la misma forma.
- `M @ P` es la **multiplicación matricial** (producto matricial) tradicional del álgebra lineal: cada elemento del resultado se calcula como la suma de los productos entre una fila completa de `M` y una columna completa de `P`. Aquí sí importa el orden y el significado de "combinar" filas con columnas, no solo posiciones equivalentes.

Por eso, aunque ambas matrices tengan la misma forma (2×2) y la operación sea "válida" en los dos casos, el resultado numérico es distinto: una combina posición con posición, la otra combina filas con columnas.

In [45]:
# 2. Verificamos si P @ M da el mismo resultado que M @ P
mult_matricial_PM = P @ M

print("P @ M:")
print(mult_matricial_PM)
print("-" * 30)
print("M @ P:")
print(mult_matricial)
print("-" * 30)
print("¿Son iguales M @ P y P @ M?:", np.array_equal(mult_matricial, mult_matricial_PM))

P @ M:
[[3.  1.5]
 [2.  6. ]]
------------------------------
M @ P:
[[3.  2. ]
 [1.5 6. ]]
------------------------------
¿Son iguales M @ P y P @ M?: False


`P @ M` **no** da el mismo resultado que `M @ P`. Ambas multiplicaciones son válidas en cuanto a forma (2×2 @ 2×2 = 2×2), pero la multiplicación matricial **no es conmutativa** en general: el orden de los factores importa, ya que cada elemento del resultado depende de combinar filas de la primera matriz con columnas de la segunda, y al invertir el orden se combinan filas y columnas distintas entre sí.

---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [46]:
# Tu código aquí

# 1. Calculamos el determinante de M con np.linalg.det()
det_M = np.linalg.det(M)
print("Determinante de M:", det_M)

# Como el determinante es distinto de 0, confirmamos que M sí tiene inversa
print("¿M tiene inversa? (determinante != 0):", det_M != 0)
print("-" * 30)

# 2. Calculamos la inversa de M con np.linalg.inv()
M_inv = np.linalg.inv(M)
print("Inversa de M:")
print(M_inv)
print("-" * 30)

# 3. Verificamos que M @ M_inv sea (aproximadamente) la matriz identidad
verificacion = M @ M_inv
print("M @ M_inv:")
print(verificacion)
print("-" * 30)

Determinante de M: 5.000000000000001
¿M tiene inversa? (determinante != 0): True
------------------------------
Inversa de M:
[[ 0.6 -0.2]
 [-0.2  0.4]]
------------------------------
M @ M_inv:
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]
------------------------------


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [47]:
b = np.array([180, 300])

# Tu código aquí

# 1. Resolvemos el sistema M @ x = b usando np.linalg.solve()
x = np.linalg.solve(M, b)
print("Solución x (unidades de cada insumo):", x)
print("-" * 30)

# 2. Verificamos multiplicando M @ x y comparando con b
verificacion = M @ x
print("M @ x:", verificacion)
print("b:", b)
print("-" * 30)


Solución x (unidades de cada insumo): [48. 84.]
------------------------------
M @ x: [180. 300.]
b: [180 300]
------------------------------


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [48]:
# Tu código aquí

# 1. Distancia euclidiana entre producto_A y producto_B, y entre producto_A y producto_C
dist_AB = np.linalg.norm(producto_A - producto_B)
dist_AC = np.linalg.norm(producto_A - producto_C)

print("Distancia euclidiana A-B:", dist_AB)
print("Distancia euclidiana A-C:", dist_AC)
print("-" * 30)

# 2. Similitud coseno entre los mismos pares: (a·b) / (||a|| ||b||)
sim_coseno_AB = (producto_A @ producto_B) / (np.linalg.norm(producto_A) * np.linalg.norm(producto_B))
sim_coseno_AC = (producto_A @ producto_C) / (np.linalg.norm(producto_A) * np.linalg.norm(producto_C))

print("Similitud coseno A-B:", sim_coseno_AB)
print("Similitud coseno A-C:", sim_coseno_AC)
print("-" * 30)

# 3. Conclusión con base en ambas métricas
# Con distancia euclidiana: menor distancia = más parecido
mas_cercano_distancia = "B" if dist_AB < dist_AC else "C"
# Con similitud coseno: mayor similitud (más cercana a 1) = más parecido
mas_cercano_coseno = "B" if sim_coseno_AB > sim_coseno_AC else "C"

coinciden = mas_cercano_distancia == mas_cercano_coseno

conclusion = (
    f"Según la distancia euclidiana, el producto más parecido a A es B\n"
    f"(distancia A-B: {dist_AB:.3f}, distancia A-C: {dist_AC:.3f}).\n"
    f"Según la similitud coseno, el producto más parecido a A es B\n"
    f"(similitud A-B: {sim_coseno_AB:.3f}, similitud A-C: {sim_coseno_AC:.3f}).\n"
    f"{'Ambas métricas coinciden.' if coinciden else 'Las métricas NO coinciden '}"
)

print(conclusion)

Distancia euclidiana A-B: 0.7071067811865476
Distancia euclidiana A-C: 5.470831746635972
------------------------------
Similitud coseno A-B: 0.9995203969214979
Similitud coseno A-C: 0.6791199021706347
------------------------------
Según la distancia euclidiana, el producto más parecido a A es B
(distancia A-B: 0.707, distancia A-C: 5.471).
Según la similitud coseno, el producto más parecido a A es B
(similitud A-B: 1.000, similitud A-C: 0.679).
Ambas métricas coinciden.


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.